stages:          # List of stages for jobs, and their order of execution
    - build
    - release

image: ubuntu:latest

build-job:
    stage: build
    tags:
        - build-product
    script:
        - ls

release-product:
    stage: release
    tags:
        - build-product
    script:
        - pwn


