stages:          # List of stages for jobs, and their order of execution
    - build
    - release
    - cleanup

build-job:
    stage: build
    tags:
        - build-product
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
          when: never
        - if: $CI_PIPELINE_SOURCE == "schedule"
          when: never
        - when: on_success
    
    before_script:
      - pip2 install resilient-sdk

    script:
        - pwd
        - resilient-sdk package -p ../$CI_PROJECT_NAME
        - mkdir ../temp
        - cp -r dist/ ../temp/
        - ls ../temp

release-product:
    stage: release
    tags:
        - build-product
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
          when: never
        - if: $CI_PIPELINE_SOURCE == "schedule"
          when: never
        - when: on_success
    
    before_script:
      - pip2 install resilient-sdk
    script:
        - cd ../temp
        - pwd
        - git clone https://gitlab.cmctssg.vn/tier2/fn_pa_firewall.git


cleanup-project:
  stage: cleanup
  tags:
    - build-product

  rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
          when: never
        - if: $CI_PIPELINE_SOURCE == "schedule"
          when: never
        - when: on_success
  script:
    - pwd
    - rm -rf ../$CI_PROJECT_NAME
    - rm -rf ../temp

