stages:          # List of stages for jobs, and their order of execution
    - build
    - release

build-job:
    stage: build
    tags:
        - build-product
    rules:
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
          when: never
    script:
        - ls

release-product:
    stage: release
    tags:
        - build-product
    rules:
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
          when: never
    script:
        - pwd


