stages:          # List of stages for jobs, and their order of execution
    - build
    - release

build-job:
    stage: build
    tags:
        - build-product
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
          when: never
        - if: $CI_PIPELINE_SOURCE == "schedule"
          when: never
        - when: on_success
    before_script:
      - pip2 install resilient-sdk

    script:
        - pwd
        - resilient-sdk package -p ../$CI_PROJECT_NAME

release-product:
    stage: release
    tags:
        - build-product
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
          when: never
        - if: $CI_PIPELINE_SOURCE == "schedule"
          when: never
        - when: on_success
    before_script:
      - pip2 install resilient-sdk
    script:
        - pwd


